### ISSUE TITLE
FATAL ERROR: Kernel too old

### ISSUE THREAD

**Issue by twaik** [amarullz/libaroma#12]
Can't build binary for kernel version <3.1.1. Used ANDROID_NDK on x64 PC and chrooted Debian on ARM tablet. It throws error `FATAL ERROR: Kernel too old
Segmentation fault` when I try to start binary.

**Comment by M1cha** [comment]
this is a common problem with new GNU toolchains. @quarx2k had that problem on motoDefy in past. The only solution is to either use old toolchains or to hack your current toolchain and hope that it will never crash.

**Comment by twaik** [comment]
solved using Linaro Toolchain
