### ISSUE TITLE
Add mediatek touch support in the aroma installer

### ISSUE THREAD

**Issue by wazeeahmed** [amarullz/libaroma#13]
I had no problems previously with aroma installer . But i tried opengapps aroma installer edition and the installer works with volume up down and power keys but not with the touch function . it has calibration issues . I touch in one point of the screen and it selects other points and then i tried using touch function again and the installer froze . Please add mediatek touch sensitivity support in your aroma installer . I am using android one sporut4 device .

**Comment by amarullz** [comment]
it's not aroma installer.
